config/routes.rb
Rails.application.routes.draw do
  resources :searches, only: [:new]
  resources :tickets

  match "/searches", to: "searches#create", via: [:get, :post]

  get "/widget.js", to: redirect{|| ActionController::Base.helpers.asset_path("widget.js") }

  root "searches#new"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :load_iframe_options
  after_action :allow_iframe

  private

  def load_iframe_options
    session[:name] = params[:name] if params[:name].present?
    session[:email] = params[:email] if params[:email].present?
    session[:fields] = params[:fields] if params[:fields].present?
    session[:chat] = ENV['ZOPIM_TOKEN'] && (params[:chat] == 'true') if params[:chat].present?
    session[:chat_department] = params[:chat_department] if params[:chat_department].present?
    session[:chat_tags] = params[:chat_tags].split(',') if params[:chat_tags].present?

    if session[:name].blank? || session[:email].blank?
      response.headers.except! 'X-Frame-Options'
      render text: "You must specify a name and email", status: :unprocessable_entity
    end
  end

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end

  def create
    @results = search_results["results"]
  end

  private

  def search_limit
    10
  end

  def search_params
    params.slice(:query, :category).merge(per_page: search_limit)
  end

  def search_results
    $zendesk.connection.get("help_center/articles/search.json", search_params).body
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
  end

  def create
    @ticket = ticket
  end

  private

  def ticket_fields
    {
        subject: params[:subject],
        comment: {
            body: params[:body]
        },
        requester: {
            locale_id: 1,
            name: session[:name],
            email: session[:email]
        },
        custom_fields: ticket_custom_fields
    }
  end

  def ticket_custom_fields
    session[:fields].map{ |id, value| {id: id.to_i, value: value} }
  end

  def ticket
    $zendesk.tickets.create(ticket_fields)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.slim
doctype 5
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    title Feedback and Support

    link href="//fonts.googleapis.com/css?family=Open+Sans:400,600" media="all" rel="stylesheet"

    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags

  body
    .container-fluid: .row = yield

    = javascript_include_tag "application"

  - if session[:chat]
    /! Zopim Live Chat
    javascript:
      window.$zopim || (function(d, s) {
        var z = $zopim = function(c) {
          z._.push(c)
        }, $ = z.s = d.createElement(s), e = d.getElementsByTagName(s)[0];
        z.set = function(o) {
          z.set._.push(o)
        };
        z._ = [];
        z.set._ = [];
        $.async = !0;
        $.setAttribute('charset', 'utf-8');
        $.src = '//v2.zopim.com/?#{ENV['ZOPIM_TOKEN']}';
        z.t = +new Date;
        $.type = 'text/javascript';
        e.parentNode.insertBefore($, e)
      })(document, 'script');

      // Zopim Live Chat Widget
      $zopim(function() {
        $zopim.livechat.set({
          language: 'en',
          name: "#{session[:name]}",
          email: "#{session[:email]}",
        });

        var chat_tags = #{{session.fetch(:chat_tags, []).to_json}};
        for (var index in chat_tags){
          $zopim.livechat.addTags(chat_tags[index]);
        }

        var chat_department = '#{session[:chat_department]}';
        if(chat_department) {
          $zopim.livechat.departments.setVisitorDepartment(chat_department);
        }

        $("#zopim-chat").on("click", function(event) {
          event.preventDefault();
          $zopim.livechat.window.show();
        });
      });

app/views/searches/create.slim
h4.search-heading Here's what we found:

.search-results
  - @results.each do |result|
    a.result href=result["html_url"] target="_blank"
      .result-title = result["title"]
      .result-body = truncate strip_tags(result["body"]), length: 100, separator: " ", escape: false

a.btn.btn-default href=new_search_path(params.slice(:category)) Go back
.pull-right
  - if session[:chat]
    a#zopim-chat.btn.btn-primary href="mailto:#{ENV['ZENDESK_EMAIL']}" Live Chat
  a.btn.btn-primary href=new_ticket_path Send a message instead

app/views/searches/new.slim
h3.title-heading Search our knowledge base

= form_tag searches_path
  = hidden_field_tag(:category, params[:category]) if params[:category]
  .input-group
    input.form-control.input-lg type="text" name="query" placeholder="What are you looking for help with?"
    span.input-group-btn: button.btn.btn-default.btn-lg type="submit" Search
    
h4.app-status
  .app-status-title #{link_to("Click here", "http://status.salesloft.com", target: "_blank")} for real-time status updates or follow us on Twitter #{link_to("@SalesLoftStatus", "https://twitter.com/salesloftstatus", target: "_blank")}

app/views/tickets/create.slim
.ticket-thanks
  h3 Your message was sent!
  p We'll be in touch shortly.

app/views/tickets/new.slim
h4.ticket-heading Send us a message

= form_tag tickets_path
  .form-group
    input.form-control type="text" name="subject" placeholder="Enter a subject for your message..."
  .form-group
    label Message
    textarea.form-control.ticket-message name="body" placeholder="Give feedback or ask for help..."
  button.btn.btn-primary type="submit" Send message